<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.curso</groupId>
        <artifactId>diccionarios</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>servicio-web</artifactId>
    <version>1.0.0</version>

    <name>Servicio web para consulta de palabras en diccionarios</name>

    <packaging>jar</packaging>

    <properties>
    <!-- 
    Aqui voy a meter (BUENA PRACTICA) las versiones de mis dependencias.
    Si necesito cambiar de versión una librería, lo cambiaré SOLO AQUI.
    -->
       <version.de.spring>4.1.0</version.de.spring>
    </properties>

    <!-- 
    Hemos dicho que este proyecto lo vamos a crear con Springboot
    Necesitamos las dependencias / librerías de springboot para servicios web 
    Este trabajo (selección de dependencias) era bastante pesado cuando no existía Springboot
    Hoy en día lo hacemos muy fácil. Con los starters de Springboot. 
    Qué es un starter? 
    Un starter es un conjunto de dependencias que nos permite hacer un tipo concreto de proyecto.
    Ejemplos:
    - spring-boot-starter-web: para crear servicios web
    - spring-boot-starter-data-jpa: para crear servicios web que acceden a bases de datos
    - spring-boot-starter-security: para crear servicios web con seguridad
    - spring-boot-starter-mongodb: para crear servicios web que acceden a bases de datos MongoDB
    - ...
    Puedo elegir varios starters.
    -->

    <dependencies>
    
        <!-- El servicio web, necesita (depende) de un suministrador de diccionarios -->
        <dependency>
            <groupId>com.curso</groupId>
            <artifactId>diccionarios-api</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.curso</groupId>
            <artifactId>diccionarios-en-ficheros</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.curso</groupId>
            <artifactId>diccionario-en</artifactId>
            <version>1.0.0</version>
        </dependency>        
        <dependency>
            <groupId>com.curso</groupId>
            <artifactId>diccionario-elfico</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.curso</groupId>
            <artifactId>diccionario-es</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
            <!-- 
            Las dependencias se descargan desde un REGISTRY DE DEPENDENCIAS
            El más usado, y el que se configura en maven por defecto, es el REGISTRY DE MAVEN CENTRAL
            Muchas empresas usan su propio registro de dependencias, para no depender de un registro externo.
            Pero, lo mantienen sincronizado con el registro de Maven Central, para que las dependencias estén disponibles.
            -->
            <version>${version.de.spring}</version>
        </dependency>
    </dependencies>
    <!-- 
    Para ayudarnos mientras desarrollamos a arrancar una aplicación creada con spring, 
    podemos configurar un plugin en maven, el plugin de SPRING
    Cuando queramos arrancar nuesta app, ejecutaremos:
    c:\...> mvn spring-boot:run
    -->

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${version.de.spring}</version>
            </plugin>
        </plugins>
    </build>
</project>